name: Android CI (Assemble Debug APK)

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      # Ставим Android SDK, платформу и build-tools гарантированно доступные на раннерах
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          api-levels: 34
          target: default
          components: build-tools;34.0.0

      # Используем системный gradle
      - name: Install Gradle
        run: |
          sudo apt-get update
          sudo apt-get install -y gradle
          gradle --version

      - name: Build Debug APK
        run: gradle :app:assembleDebug --no-daemon --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
